docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - Pages: pages.md
        - Containers: containers.md
    - View Helpers:
        - Introduction: helpers/intro.md
        - Breadcrumbs: helpers/breadcrumbs.md
        - Links: helpers/links.md
        - Menu: helpers/menu.md
        - Sitemap: helpers/sitemap.md
        - "Navigation Proxy": helpers/navigation.md
site_name: laminas-navigation
site_description: "Manage trees of pointers to web pages in order to build navigation systems."
repo_url: 'https://github.com/laminas/laminas-navigation'
extra:
    project: Components
    project_url: 'https://docs.laminas.dev'
